### ISSUE TITLE
MySQL Error when Activating Plugin

### ISSUE THREAD

**Issue by AutoJunkie79** [SvePu/MyBB-Rename-First-Navbit#2]
Downloaded your latest package from official MyBB mod site, however upon attempting to activate the plugin, I received a MySQL error. Running MyBB 1.8.10 on PHP 7.1 w/ MySQL 5.7.17.

![capture](https://cloud.githubusercontent.com/assets/25411186/22593333/f7f0f040-e9eb-11e6-8989-5477e112ff3c.PNG)

**Comment by SvePu** [comment]
@AutoJunkie79 - Hey...thanks for your hint...I'll check and fix the issue as soon as possible.

**Comment by SvePu** [comment]
Done!

**Comment by AutoJunkie79** [comment]
Thanks so much for the quick turnaround, you are awesome. Confirmed working as well!
